version: '3'

services:
  app:
    image: raspeye
    network_mode: "host"
    ports:
    - "80:80"
    restart: always
    logging:
      driver: "awslogs"
      options:
        awslogs-region: us-west-2
        awslogs-group: raspeye
        awslogs-stream: app
        awslogs-create-group: "true"


  nginx:
    image: nginx-proxy
    network_mode: "host"
    ports:
    - "443:443"
    - "8443:8443"
    environment:
      NGINX_SERVER_NAME: "eagleye.trendops.co"
      NGINX_UPSTREAM_HOST: 127.0.0.1
      NGINX_UPSTREAM_PORT: 80
    volumes:
    - /home/ubuntu/eagleye/ssl/:/etc/nginx/ssl
    restart: always
    depends_on:
    - app
    logging:
      driver: "awslogs"
      options:
        awslogs-region: us-west-2
        awslogs-group: raspeye
        awslogs-stream: nginx
        awslogs-create-group: "true"
